/*
PDF Generator API

Testing TemplateLibraryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pdfgeneratorapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pdfgeneratorapi/go-client/v4"
)

func Test_pdfgeneratorapi_TemplateLibraryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TemplateLibraryAPIService GetTemplateLibrary", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TemplateLibraryAPI.GetTemplateLibrary(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TemplateLibraryAPIService GetTemplateLibraryItem", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var publicId string

		resp, httpRes, err := apiClient.TemplateLibraryAPI.GetTemplateLibraryItem(context.Background(), publicId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
