/*
PDF Generator API

Testing FormsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pdfgeneratorapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pdfgeneratorapi/go-client/v4"
)

func Test_pdfgeneratorapi_FormsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FormsAPIService CreateForm", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FormsAPI.CreateForm(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FormsAPIService DeleteForm", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var formId int32

		httpRes, err := apiClient.FormsAPI.DeleteForm(context.Background(), formId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FormsAPIService GetForm", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var formId int32

		resp, httpRes, err := apiClient.FormsAPI.GetForm(context.Background(), formId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FormsAPIService GetForms", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FormsAPI.GetForms(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FormsAPIService ImportForm", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FormsAPI.ImportForm(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FormsAPIService OpenFormBuilder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FormsAPI.OpenFormBuilder(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FormsAPIService OpenFormBuilderForExistingForm", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var formId int32

		resp, httpRes, err := apiClient.FormsAPI.OpenFormBuilderForExistingForm(context.Background(), formId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FormsAPIService ShareForm", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var formId int32

		resp, httpRes, err := apiClient.FormsAPI.ShareForm(context.Background(), formId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FormsAPIService UpdateForm", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var formId int32

		resp, httpRes, err := apiClient.FormsAPI.UpdateForm(context.Background(), formId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
