/*
PDF Generator API

Testing TemplateVersionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pdfgeneratorapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pdfgeneratorapi/go-client/v4"
)

func Test_pdfgeneratorapi_TemplateVersionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TemplateVersionsAPIService DeleteTemplateVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var templateId int32
		var templateVersion int32

		httpRes, err := apiClient.TemplateVersionsAPI.DeleteTemplateVersion(context.Background(), templateId, templateVersion).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TemplateVersionsAPIService GetTemplateVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var templateId int32
		var templateVersion int32

		resp, httpRes, err := apiClient.TemplateVersionsAPI.GetTemplateVersion(context.Background(), templateId, templateVersion).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TemplateVersionsAPIService ListTemplateVersions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var templateId int32

		resp, httpRes, err := apiClient.TemplateVersionsAPI.ListTemplateVersions(context.Background(), templateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TemplateVersionsAPIService PromoteTemplateVersion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var templateId int32
		var templateVersion int32

		resp, httpRes, err := apiClient.TemplateVersionsAPI.PromoteTemplateVersion(context.Background(), templateId, templateVersion).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
