/*
PDF Generator API

Testing WorkspacesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package pdfgeneratorapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pdfgeneratorapi/go-client/v8"
)

func Test_pdfgeneratorapi_WorkspacesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WorkspacesAPIService CreateWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WorkspacesAPI.CreateWorkspace(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService DeleteWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceIdentifier string

		httpRes, err := apiClient.WorkspacesAPI.DeleteWorkspace(context.Background(), workspaceIdentifier).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService GetWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceIdentifier string

		resp, httpRes, err := apiClient.WorkspacesAPI.GetWorkspace(context.Background(), workspaceIdentifier).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService GetWorkspaces", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WorkspacesAPI.GetWorkspaces(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
